name: Build LaTeX document
on: [ push, workflow_dispatch ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Install TeXlive
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive latexmk
          version: 1.0
      - name: LaTeX compile
        run: latexmk
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: ./out/*.pdf
